Package                       Version
----------------------------- ---------
asttokens                     2.0.8
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
brotlipy                      0.7.0
certifi                       2022.9.14
cffi                          1.15.1
charset-normalizer            2.0.4
colorama                      0.4.5
contourpy                     1.0.5
cryptography                  37.0.1
cycler                        0.11.0
debugpy                       1.6.3
decorator                     5.1.1
entrypoints                   0.4
executing                     1.0.0
fonttools                     4.37.3
idna                          3.3
ipykernel                     6.15.3
ipython                       8.5.0
jedi                          0.18.1
jupyter_client                7.3.5
jupyter_core                  4.11.1
kiwisolver                    1.4.4
matplotlib                    3.6.0
matplotlib-inline             0.1.6
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
nest-asyncio                  1.5.5
numpy                         1.23.1
packaging                     21.3
parso                         0.8.3
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.1.2
prompt-toolkit                3.0.31
psutil                        5.9.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.13.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-dateutil               2.8.2
pywin32                       303
pyzmq                         23.2.0
requests                      2.28.1
setuptools                    63.4.1
six                           1.16.0
stack-data                    0.5.0
torch                         1.12.1
torchaudio                    0.12.1
torchvision                   0.13.1
tornado                       6.2
traitlets                     5.4.0
typing_extensions             4.3.0
urllib3                       1.26.11
wcwidth                       0.2.5
wheel                         0.37.1
win-inet-pton                 1.1.0
wincertstore                  0.2
